/**
 * lib/insights.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * Pure calculation functions for the Smart Insights panel.
 * No UI, no side-effects — just transforms a Subscription[] into an Insights object.
 *
 * HOW TO EXTEND
 * ─────────────────────────────────────────────────────────────────────────────
 * 1. Add a new field to the `Insights` type below.
 * 2. Compute it inside `computeInsights` using the helpers already defined.
 * 3. Pass the new field through `InsightsPanel` to a new card — no other file
 *    needs to change.
 */

import type { Subscription } from '@/components/DashboardClient'

// ─── Helpers ─────────────────────────────────────────────────────────────────

/** Monthly-equivalent cost for a subscription regardless of billing cycle. */
function monthlyEq(sub: Subscription): number {
  return sub.billingCycle === 'yearly' ? sub.price / 12 : sub.price
}

// ─── Output types ─────────────────────────────────────────────────────────────

export type InsightCategory = {
  /** Raw category string as stored (e.g. "entertainment") */
  name: string
  /** Sum of monthly-equivalent costs for this category */
  monthly: number
  /** Number of subscriptions in this category */
  count: number
}

export type TopSub = {
  name: string
  /** Monthly-equivalent cost */
  monthly: number
}

export type InsightRenewal = {
  /** Number of subscriptions renewing within the next 7 days */
  count: number
  /** Sum of the actual charge amounts (not monthly equivalent) for those renewals */
  total: number
  /** The subscription names, sorted by billing date, for display */
  names: string[]
  /**
   * Days until the soonest renewal (0 = today). Null when count === 0.
   * Used to determine urgency level (urgent / upcoming / clear).
   */
  soonestDays: number | null
}

export type SaveHint = {
  /** Name of the cheapest subscription */
  name: string
  /** Its annualised cost — what cancelling it would save per year */
  yearlyCost: number
}

export type Insights = {
  totalMonthly: number
  totalYearly: number
  /** Category with the highest combined monthly spend, or null if no categories are set */
  topCategory: InsightCategory | null
  /** Up to 3 subscriptions sorted by monthly equivalent (highest first) */
  top3: TopSub[]
  renewal: InsightRenewal
  /**
   * Percentage change in monthly spend vs ~30 days ago, rounded to nearest integer.
   * Estimated from createdAt: subscriptions added in the last 30 days weren't
   * in last month's total. Null when there's no prior data to compare against.
   */
  trendPercent: number | null
  /**
   * The cheapest subscription surfaced as a potential cut.
   * Null when there are 0 or 1 subscriptions (nothing actionable to suggest).
   */
  savingsHint: SaveHint | null
  /**
   * 1–3 plain-English observations generated by simple rules (no AI API).
   * Always contains at least one entry when subscriptions.length > 0.
   */
  aiInsights: string[]
}

// ─── Main function ────────────────────────────────────────────────────────────

export function computeInsights(subscriptions: Subscription[]): Insights {
  const today = new Date()
  today.setHours(0, 0, 0, 0)

  // ── Totals ──────────────────────────────────────────────────────────────────
  const totalMonthly = subscriptions.reduce((sum, s) => sum + monthlyEq(s), 0)
  const totalYearly = subscriptions.reduce(
    (sum, s) => sum + (s.billingCycle === 'yearly' ? s.price : s.price * 12),
    0
  )

  // ── Trend vs last month ─────────────────────────────────────────────────────
  // Subscriptions created ≥ 30 days ago represent last month's portfolio.
  // This is an approximation; it doesn't account for price edits or deletions.
  const oneMonthAgo = new Date(today)
  oneMonthAgo.setMonth(oneMonthAgo.getMonth() - 1)

  const priorSubs = subscriptions.filter(s => new Date(s.createdAt) <= oneMonthAgo)
  const priorTotal = priorSubs.reduce((sum, s) => sum + monthlyEq(s), 0)
  const trendPercent =
    priorSubs.length > 0 && priorTotal > 0
      ? Math.round(((totalMonthly - priorTotal) / priorTotal) * 100)
      : null

  // ── Category breakdown ──────────────────────────────────────────────────────
  const catMap = new Map<string, { monthly: number; count: number }>()
  for (const sub of subscriptions) {
    const cat = sub.category ?? 'other'
    const prev = catMap.get(cat) ?? { monthly: 0, count: 0 }
    catMap.set(cat, {
      monthly: prev.monthly + monthlyEq(sub),
      count: prev.count + 1,
    })
  }

  let topCategory: InsightCategory | null = null
  catMap.forEach((data, name) => {
    if (!topCategory || data.monthly > topCategory.monthly) {
      topCategory = { name, ...data }
    }
  })

  // ── Top 3 subscriptions ─────────────────────────────────────────────────────
  const top3: TopSub[] = [...subscriptions]
    .sort((a, b) => monthlyEq(b) - monthlyEq(a))
    .slice(0, 3)
    .map(s => ({ name: s.name, monthly: monthlyEq(s) }))

  // ── Renewal warning ─────────────────────────────────────────────────────────
  const cutoff = new Date(today)
  cutoff.setDate(cutoff.getDate() + 7)

  const upcomingSubs = subscriptions
    .filter(s => {
      const d = new Date(s.nextBilling)
      d.setHours(0, 0, 0, 0)
      return d >= today && d <= cutoff
    })
    .sort((a, b) => new Date(a.nextBilling).getTime() - new Date(b.nextBilling).getTime())

  const soonestDays: number | null =
    upcomingSubs.length > 0
      ? (() => {
          const d = new Date(upcomingSubs[0].nextBilling)
          d.setHours(0, 0, 0, 0)
          return Math.round((d.getTime() - today.getTime()) / (1000 * 60 * 60 * 24))
        })()
      : null

  const renewal: InsightRenewal = {
    count: upcomingSubs.length,
    total: upcomingSubs.reduce((sum, s) => sum + s.price, 0),
    names: upcomingSubs.map(s => s.name),
    soonestDays,
  }

  // ── Savings hint ─────────────────────────────────────────────────────────────
  // Surface the cheapest subscription as a potential cut — only meaningful when
  // there's more than one (otherwise it's "cancel your only subscription").
  let savingsHint: SaveHint | null = null
  if (subscriptions.length > 1) {
    const cheapest = [...subscriptions].sort((a, b) => monthlyEq(a) - monthlyEq(b))[0]
    savingsHint = {
      name: cheapest.name,
      yearlyCost:
        cheapest.billingCycle === 'yearly' ? cheapest.price : cheapest.price * 12,
    }
  }

  // ── AI-style insights (rule-based, no external API) ─────────────────────────
  // Rules are evaluated in priority order; we keep at most 3.
  const fmt = (n: number) =>
    new Intl.NumberFormat('en-US', { style: 'currency', currency: 'EUR', minimumFractionDigits: 2 }).format(n)

  const aiInsights: string[] = []

  // Rule 1 — duplicate category (3+ subs in the same category)
  catMap.forEach((data, name) => {
    if (aiInsights.length < 3 && data.count >= 3) {
      const label = name.charAt(0).toUpperCase() + name.slice(1)
      aiInsights.push(
        `You have ${data.count} subscriptions in "${label}" — do you really need all of them? 🤔`
      )
    }
  })

  // Rule 2 — high monthly spending
  if (aiInsights.length < 3 && totalMonthly > 200) {
    aiInsights.push(
      `You're spending ${fmt(totalMonthly)}/mo on subscriptions 😳 — that's ${fmt(totalYearly)} a year.`
    )
  }

  // Rule 3 — surface the most expensive subscription
  if (aiInsights.length < 3 && top3.length > 0) {
    aiInsights.push(
      `Your most expensive subscription is ${top3[0].name} at ${fmt(top3[0].monthly)}/mo.`
    )
  }

  // Rule 4 — savings nudge (cheapest sub, easiest cut)
  if (aiInsights.length < 3 && savingsHint) {
    aiInsights.push(
      `Canceling ${savingsHint.name} could save you ${fmt(savingsHint.yearlyCost)}/year 💡`
    )
  }

  return { totalMonthly, totalYearly, topCategory, top3, renewal, trendPercent, savingsHint, aiInsights }
}
